<?php
declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: dedipyaman
 * Date: 8/31/18
 * Time: 1:26 AM
 */

namespace GreenTea\Phypes\Type;

use GreenTea\Phypes\Validator\Validator;
use PHPUnit\Framework\TestCase;
use Mockery;

final class EmailTest extends TestCase
{

    private $email;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testImplementsTypeInterface()
    {
        $this->assertInstanceOf(Type::class, $this->getValidEmail());
    }

    public function testGetValue()
    {
        $email = $this->getValidEmail();
        $this->assertEquals('email@example.com', $email->getValue());
    }

    private function getValidEmail() : Email
    {
        $validator = Mockery::mock(Validator::class);
        $validator->allows()->isValid("email@example.com")->andReturns(true);

        $email = new Email("email@example.com", $validator);
        return $email;
    }
}
